package cs1302.arcade;

import java.util.Random;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.shape.Rectangle;
import javafx.animation.Animation;
import javafx.animation.Timeline;
import javafx.animation.KeyFrame;
import javafx.stage.Stage;
import javafx.event.EventHandler;
import javafx.event.ActionEvent;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.KeyCode;
import javafx.scene.input.MouseEvent;
<<<<<<< HEAD
import javafx.scene.layout.VBox;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.layout.HBox;
import javafx.scene.control.MenuItem;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
=======
import javafx.util.Duration;
>>>>>>> 19bde5e3b0dd60a11ef9f5c481a12e4db2ab4caf

/**
 * Application subclass for {@code ArcadeApp}.
 * @version 2019.fa
 */
public class ArcadeApp extends Application {

    Group group = new Group();           // main container
    Random rng = new Random();           // random number generator
    Rectangle r = new Rectangle(20, 20); // some rectangle
<<<<<<< HEAD

    // main menu variables
    Vbox vBox;
    HBox cContainer;
    Hbox rContainer;
    Scene menuScene;
    Scene cScene;
    Scene rScene;
    Menu menu;
    MenuItem exit;
    MenuBar menuBar;
    Button cButton; // centipede start
    Button rButton; // reversi start
    TextField cInstructions;
    TextField rInstructions;


    // event handlers
=======
    Rectangle e = new Rectangle(20, 20); // temp enemy rectangel
    boolean daemon = true;
    boolean rightE = true;
    boolean upE = false;
    int eSpeed = 10;
    final Timeline timeline = gamePlayLoop();
>>>>>>> 19bde5e3b0dd60a11ef9f5c481a12e4db2ab4caf
    /**
     * Return a mouse event handler that moves to the rectangle to a random
     * position any time a mouse event is generated by the associated node.
     * @return the mouse event handler
     */
    private EventHandler<? super MouseEvent> createMouseHandler() {
        return event -> {
            System.out.println(event);
            r.setX(rng.nextDouble() * (640 - r.getWidth()));
            r.setY(rng.nextDouble() * (480 - r.getHeight()));
        };
    } // createMouseHandler

    private Timeline gamePlayLoop() {


        final Duration oneFrameAmt = Duration.millis(1000/60);
        final KeyFrame oneFrame = new KeyFrame(oneFrameAmt,
                                               new EventHandler<ActionEvent>() {
                                                 public void handle(ActionEvent event) {
                if(!upE && e.getX() > 600) {
                    e.setY(e.getY() + eSpeed);
                    rightE = false;
                } else if(!upE && e.getX() <= 0.0) {
                    e.setY(e.getY() + eSpeed);
                    rightE = true;
                }
                if(rightE) {
                    e.setX(e.getX() + eSpeed);
                } else {
                    e.setX(e.getX() - eSpeed);
                } //else
        System.out.println("x value: " + e.getX());
        System.out.println("Y value: " + e.getY());
                if(e.getY()  > 440){
                    upE = true;
                }
                if(upE && e.getY() < 380) {
                    upE = false;
                }
                if(upE == true &&e.getX() > 600) {
                    e.setY(e.getY() -eSpeed);
                    rightE = false;
                } else if(upE && e.getX() <= 0.0) {
                    e.setY(e.getY() - eSpeed);
                    rightE = true;
                }
                                                 }
            }); // oneFrame
        Timeline timeline = new Timeline();
        timeline.setCycleCount(Animation.INDEFINITE);
        timeline.getKeyFrames().add(oneFrame);
        return timeline;
    } //
    /**
     * Return a key event handler that moves to the rectangle to the left
     * or the right depending on what key event is generated by the associated
     * node.
     * @return the key event handler
     */
    private EventHandler<? super KeyEvent> createKeyHandler() {
        return event -> {
            System.out.println(event);
            switch (event.getCode()) {
            case LEFT:  // KeyCode.LEFT
                if(r.getX() <= 0 ) {
                    r.setX(0.0);
                } else {
                    r.setX(r.getX() - 10.0);
                } //else
                break;
            case RIGHT: // KeyCode.RIGHT
                if(r.getX() > 600) {
                    r.setX(620);
                } else {
                    r.setX(r.getX() + 10.0);
                } //else
                break;
            case UP:
                if(r.getY() < 380) {
                    r.setY(360);
                } else {
                    r.setY(r.getY() - 10);
                }
                break;
            case DOWN:
                if(r.getY() > 440) {
                    r.setY(460);
                } else {
                    r.setY(r.getY() + 10);
                }
                break;
            default:
                // do nothing
            } // switch
            // TODO bounds checking
        };
    } // createKeyHandler

    private EventHandler<ActionEvent> exitApp = new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent e) {
                System.exit(0);
            }
        };

    private EventHandler<ActionEvent> startCentipede = new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent e) {
                stage.setTitle("Centipede");
                stage.setScene(cScene);
                stage.sizeToScene();
                stage.show();
            }
        };

    private EventHandler<ActionEvent> startReversi = new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent e) {
                stage.setTitle("Reversi");
                stage.setScene(rScene);
                stage.sizeToScene();
                stage.show();
            }
        };

    /** {@inheritDoc} */
    @Override
    public void start(Stage stage) {
<<<<<<< HEAD

        vBox = new vBox();
        cContainer = new HBox();
        rContainer = new Hbox();
        menuScene = new Scene(vBox, 640, 480);
        cScene = new Scene(640, 480);
        rScene = new Scene(640, 480);
        menu = new Menu("File");
        exit = new MenuItem("Exit");
        menuBar = new menuBar();
        cButton = new Button("Centipede");
        rButton = new Button("Reversi");
        cInstructions = new TextField("Fill in later");
        rInstructions = new TextField("Fill in later");

        // add children to parents
        cContainer.getChildren().addAll(cButton, cInstructions);
        rContainer.getChildren().addAll(rButton, rInstructions);
        menu.getItems().add(exit);
        menuBar.getMenus().add(menu);
        vBox.getChildren().addAll(menuBar, cContainer, rContainer);
        group.getChildren().add(r);                // add to main container

        // generate events
//        r.setOnMouseClicked(createMouseHandler()); // clicks on the rectangle move it randomly
        group.setOnKeyPressed(createKeyHandler()); // left-right key presses move the rectangle
        menu.setOnAction(exitApp);
        cButton.setOnAction(startCentipede);
        rButton.setOnAction(startReversi);

        //      Scene scene = new Scene(group, 640, 480);
=======
        group.getChildren().addAll(r, e);                // add to main container
        group.setOnKeyPressed(createKeyHandler());
>>>>>>> 19bde5e3b0dd60a11ef9f5c481a12e4db2ab4caf
        Scene centiped = centipede();
        stage.setTitle("cs1302-arcade!");
        stage.setScene(centiped);
        stage.sizeToScene();

        stage.show();

        // the group must request input focus to receive key events
        // @see https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#requestFocus--
        group.requestFocus();

    } // start

    public static void runOnNewThread(boolean daemon, Runnable target) {
        Thread t = new Thread(target);
        t.setDaemon(daemon);
        t.start();
                       } // runOnNewThread

    private Scene centipede() {
        Scene centipede = new Scene(group, 640, 480);
        r.setX(320);
        r.setY(460);
        e.setX(100);
        e.setY(240);
        timeline.play();
        return centipede;
    } //centipede

} // ArcadeApp
